# gentoo-ing-packages - curated Gentoo binary package host (binhost) for gentoo-ing.
#
# This is a data-only image: its only content is the binhost tree under
# /var/cache/binhost/gentoo-ing (binary packages + a fresh `Packages` index,
# regenerated by `emaint binhost --fix`). gentoo-ing consumes it with
# `COPY --from=...` pinned by digest, the same way the finpilot factory pulls
# projectbluefin/common and ublue-os/brew.
#
# Drop `.tbz2` files into `packages/` (the "plop in newer packages" workflow):
#   - build/emerge one, or download it (see tools/seed-binhost.sh)
#   - place it under packages/ preserving the official layout
#     (<category>/<pkg>-<version>.tbz2)
#   - push; CI regenerates the index and publishes a new :latest

# Base image providing Portage (emaint). Pinned by Renovate in this FROM line.
ARG GENTOO_IMAGE="gentoo/stage3:systemd"
FROM ${GENTOO_IMAGE} AS indexer

# The binhost location. Matches the `location` key that consumers configure in
# /etc/portage/binrepos.conf.
ENV PKGDIR="/var/cache/binhost/gentoo-ing"

# Portage >=3.0.52 defaults to FEATURES=pkgdir-index-trusted which assumes the
# Packages index is accurate; we regenerate it below so nothing stale matters.
COPY packages "${PKGDIR}"

# Regenerate the Packages index from whatever is in the tree. Keep the build
# strict: a corrupt tbz2 breaks the image so it never reaches consumers.
RUN mkdir -p "${PKGDIR}" \
    && if find "${PKGDIR}" -name '*.tbz2' | grep -q .; then \
        emaint binhost --fix; \
    fi \
    && test -f "${PKGDIR}/Packages" || echo "PACKAGES: <empty overlay>" > "${PKGDIR}/Packages"

# Publish only the binhost tree.
FROM scratch AS binhost

COPY --from=indexer /var/cache/binhost/gentoo-ing /var/cache/binhost/gentoo-ing