spec_version: "49.1"
upstream:
  vcs: github
  upstream: GNOME/gsettings-desktop-schemas
  package-name: gsettings-desktop-schemas
  tag-template: "{version}"
  version: "49.1"
  archive-template: "https://download.gnome.org/sources/gsettings-desktop-schemas/49/gsettings-desktop-schemas-49.1.tar.xz"
package:
  description: ""
  homepage: https://wiki.gnome.org/Projects/gsettings-desktop-schemas
  license: ""
  keywords: "~amd64"
  maintainer_email: gentoo-ing@huntedraven.com
  maintainer_name: gentoo-ing
downstream:
  - url: git@github.com:HuntedRaven7/gentoo-ing-packages.git
    branch: main
    category: gnome-base
    package-dir: ebuilds
open_pull_request: false
